[features]
seeds = false
skip-lint = false
[programs.localnet]
strawsoll = "6s5JqB54MEjW6SX4AtYgWQJEsLKj6C1Q5pj1LCD6PnY7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ito/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000